/**
 * Case — a successful (or failed) task record in the experience system.
 *
 * Cases capture the outcome of applying tactics to a specific task.
 * They serve as training material for the slow loop (`/fine-tune`)
 * and as validation evidence for tactic effectiveness in the fast loop.
 *
 * Each case links a task signature (what was being done), the tactics
 * that were injected, the signals that fired, and the final verdict.
 * This creates a complete feedback loop for continuous improvement.
 *
 * @module experience/case
 */

import type { Signal } from "../evolve/signals"

/**
 * Outcome of a task execution with tactic injection.
 *
 * - `pass`:    Task completed successfully with tactic help
 * - `fail`:    Task failed despite tactic injection
 * - `partial`: Task partially completed or had mixed results
 */
export type CaseVerdict = "pass" | "fail" | "partial"

/**
 * A Case captures one complete task → tactic → outcome cycle.
 *
 * Cases are the primary feedback mechanism for the experience system.
 * When a tactic is injected and a task completes, a Case is created
 * recording what happened. Over time, cases accumulate evidence for
 * or against each tactic's effectiveness.
 *
 * The `taskSignature` is a hash/fingerprint of the task description,
 * enabling grouping of similar tasks without storing sensitive content.
 */
export interface Case {
	/**
	 * Unique case identifier.
	 * Format: `case_<timestamp>_<random}` — generated by `createCase`.
	 */
	readonly id: string

	/**
	 * Hash or fingerprint of the task description.
	 * Enables grouping similar tasks without storing the original (potentially
	 * sensitive) task content. Computed by the caller before `createCase`.
	 */
	readonly taskSignature: string

	/** ID of the session during which this case was recorded. */
	readonly sessionId: string

	/** IDs of tactics that were injected for this task. */
	readonly tacticIds: string[]

	/** Final outcome of the task. */
	readonly verdict: CaseVerdict

	/** Performance metrics for this task execution. */
	readonly metrics: {
		/** Wall-clock time in milliseconds. */
		readonly durationMs: number

		/** Number of tool calls made during execution. */
		readonly toolCalls: number

		/** Number of retry attempts. */
		readonly retries: number
	}

	/** Signals that triggered tactic injection for this case. */
	readonly signals: Signal[]

	/** ISO 8601 timestamp of case creation. */
	readonly createdAt: string

	/** Whether PII has been scrubbed from this case. */
	readonly scrubbed: boolean
}

/**
 * Parameters for creating a new Case (all fields except auto-generated ones).
 */
export interface CreateCaseParams {
	/** Hash/fingerprint of the task description. */
	readonly taskSignature: string

	/** Session ID where the case was recorded. */
	readonly sessionId: string

	/** Tactic IDs injected during the task. */
	readonly tacticIds: string[]

	/** Final outcome. */
	readonly verdict: CaseVerdict

	/** Performance metrics. */
	readonly metrics: {
		readonly durationMs: number
		readonly toolCalls: number
		readonly retries: number
	}

	/** Signals that triggered injection. */
	readonly signals: Signal[]

	/** Whether PII has been scrubbed. */
	readonly scrubbed: boolean
}

/**
 * Create a new Case with auto-generated `id` and `createdAt`.
 *
 * The ID format is `case_<timestamp>_<randomHex>` for chronological
 * ordering and uniqueness. The `createdAt` field is set to the
 * current time in ISO 8601 format.
 *
 * @param params - All case fields except `id` and `createdAt`
 * @returns A complete Case ready for persistence
 *
 * @example
 * ```typescript
 * const c = createCase({
 *   taskSignature: "sha256:abc123...",
 *   sessionId: "sess_20240115_001",
 *   tacticIds: ["tac_global_a3f7e2b1"],
 *   verdict: "pass",
 *   metrics: { durationMs: 45000, toolCalls: 12, retries: 1 },
 *   signals: [signal1, signal2],
 *   scrubbed: true,
 * })
 * ```
 */
export function createCase(params: CreateCaseParams): Case {
	const timestamp = Date.now()
	const randomHex = Math.random().toString(36).slice(2, 8)
	const id = `case_${timestamp}_${randomHex}`
	const createdAt = new Date(timestamp).toISOString()

	return {
		id,
		taskSignature: params.taskSignature,
		sessionId: params.sessionId,
		tacticIds: params.tacticIds,
		verdict: params.verdict,
		metrics: params.metrics,
		signals: params.signals,
		createdAt,
		scrubbed: params.scrubbed,
	}
}
