import * as fs from "fs"
import * as path from "path"

const srcDir = path.resolve(import.meta.dir, "..", "src", "serve")
const outFile = path.join(srcDir, "assets.generated.ts")

const dashboard = fs.readFileSync(path.join(srcDir, "dashboard.html"), "utf-8")
const workbench = fs.readFileSync(path.join(srcDir, "workbench.html"), "utf-8")

const code = `// AUTO-GENERATED by scripts/embed-assets.ts — do not edit manually.
// Embeds HTML assets so compiled Bun binaries can serve them without filesystem access.

export const DASHBOARD_HTML: string = ${JSON.stringify(dashboard)}

export const WORKBENCH_HTML: string = ${JSON.stringify(workbench)}
`

fs.writeFileSync(outFile, code, "utf-8")
console.log(`✅ Embedded assets → ${path.relative(process.cwd(), outFile)} (${(code.length / 1024).toFixed(0)} KB)`)
