/**
 * Provenance Ledger — data-curation.md style logging.
 *
 * Records for each promotion:
 * - Dataset version, slice ratios, quality controls applied
 * - Confusion clusters used, number of samples per cluster
 * - Hyperparameters and learning strategy
 * - Eval scores, regression counts
 * - Approval metadata (who, when)
 *
 * Survives context compression — the audit trail of self-evolution.
 *
 * Reference: Pioneer Agent §2.8 — "Provenance tracking ensures every
 * training decision is auditable and reproducible."
 */
import { Effect, Ref } from "effect"
import { Option } from "effect"
import type { MCGraph, MCNode, EvalScore } from "./index"

export interface ProvenanceEntry {
  readonly timestamp: Date
  readonly modelId: string
  readonly action: "staged" | "promoted" | "rejected" | "rolled_back"
  readonly datasetVersion: string
  readonly goldCount: number
  readonly hardNegCount: number
  readonly replayCount: number
  readonly clusters: ReadonlyArray<string>
  readonly hyperparams: {
    readonly baseModel: string
    readonly loraRank: number
    readonly learningRate: number
    readonly epochs: number
    readonly batchSize: number
    readonly format: string
  }
  readonly evalScore: EvalScore
  readonly approvedBy?: string
  readonly notes: string
  readonly iteration: number
  readonly depth: number
}

/**
 * Provenance service — maintains the audit trail of all training decisions.
 *
 * Each entry records the full state of a training iteration:
 * what data was used, what hyperparameters were set, what the
 * outcome was, and who approved it.
 */
export class Provenance extends Effect.Service<Provenance>()("evolve/Provenance", {
  effect: Effect.gen(function* () {
    const entriesRef = yield* Ref.make<ReadonlyArray<ProvenanceEntry>>([])

    /**
     * Record a provenance entry for a graph node.
     *
     * Captures the full pipeline state: data slices, hyperparameters,
     * evaluation scores, and action taken.
     */
    const append = (
      graph: MCGraph,
      node: MCNode,
      action: ProvenanceEntry["action"],
    ) =>
      Effect.gen(function* () {
        const score =
          node.score._tag === "Some"
            ? node.score.value
            : {
                passAt1: 0,
                regressionCount: 0,
                calibratedConfidence: 0,
                safetyScore: 0,
              }

        const entry: ProvenanceEntry = {
          timestamp: new Date(),
          modelId: node.pi.H.baseModel,
          action,
          datasetVersion: `v${graph.iteration}`,
          goldCount: node.pi.D.gold.length,
          hardNegCount: node.pi.D.hardNegatives.length,
          replayCount: node.pi.D.replay.length,
          clusters: [], // Would be filled from taxonomy in production
          hyperparams: {
            baseModel: node.pi.H.baseModel,
            loraRank: node.pi.H.loraRank,
            learningRate: node.pi.H.learningRate,
            epochs: node.pi.H.epochs,
            batchSize: node.pi.H.batchSize,
            format: node.pi.S.format,
          },
          evalScore: score,
          notes: `MCGS iteration ${graph.iteration}, depth ${node.depth}, visits ${node.visits}`,
          iteration: graph.iteration,
          depth: node.depth,
        }

        yield* Ref.update(entriesRef, (e) => [...e, entry])

        // Also write to data-curation.md for persistence
        yield* writeDataCurationMd(entry)

        yield* Effect.log(
          `[Provenance] Recorded: ${action} ${entry.modelId} @ ${entry.datasetVersion}`,
        )
      })

    /**
     * List all provenance entries.
     */
    const list = () => Ref.get(entriesRef)

    /**
     * Generate a full data-curation.md report.
     */
    const generateReport = () =>
      Effect.gen(function* () {
        const entries = yield* Ref.get(entriesRef)

        const header = `# Data Curation Ledger\n\n> Auto-generated by momo Code Self-Evolution System\n> Total entries: ${entries.length}\n\n`

        const sections = entries.map((e) => formatEntryAsMarkdown(e))

        return header + sections.join("\n---\n\n")
      })

    return { append, list, generateReport } as const
  }),
  dependencies: [],
}) {}

/**
 * Write a provenance entry to the data-curation.md file.
 *
 * In production, this appends to `.momo/data-curation.md`.
 * The file serves as the audit trail that survives context compression.
 */
function writeDataCurationMd(entry: ProvenanceEntry): Effect.Effect<void, never> {
  return Effect.sync(() => {
    const actionEmoji = {
      staged: "📋",
      promoted: "🚀",
      rejected: "❌",
      rolled_back: "↩️",
    }

    const line = `
## ${actionEmoji[entry.action]} ${entry.timestamp.toISOString()} — ${entry.action.toUpperCase()}

- **Model**: ${entry.modelId}
- **Dataset**: ${entry.datasetVersion}
  - Gold: ${entry.goldCount}
  - Hard-negatives: ${entry.hardNegCount}
  - Replay: ${entry.replayCount}
- **Eval**: pass@1=${(entry.evalScore.passAt1 * 100).toFixed(1)}%, regressions=${entry.evalScore.regressionCount}, safety=${(entry.evalScore.safetyScore * 100).toFixed(1)}%
- **Hyperparams**: LoRA r=${entry.hyperparams.loraRank}, lr=${entry.hyperparams.learningRate}, epochs=${entry.hyperparams.epochs}, batch=${entry.hyperparams.batchSize}
- **Approved by**: ${entry.approvedBy || "N/A"}
- **Notes**: ${entry.notes}
`.trim()

    // In production: append to .momo/data-curation.md
    // fs.appendFileSync(".momo/data-curation.md", line + "\n\n")

    // For now, log to console
    console.log("[data-curation.md] " + line.replace(/\n/g, "\n[data-curation.md] "))
  })
}

/**
 * Format a provenance entry as markdown for the report.
 */
function formatEntryAsMarkdown(entry: ProvenanceEntry): string {
  const actionEmoji = {
    staged: "📋",
    promoted: "🚀",
    rejected: "❌",
    rolled_back: "↩️",
  }

  return `### ${actionEmoji[entry.action]} ${entry.timestamp.toISOString()}

**Action**: ${entry.action}
**Model**: \`${entry.modelId}\`
**Dataset**: ${entry.datasetVersion} (${entry.goldCount} gold / ${entry.hardNegCount} hard-neg / ${entry.replayCount} replay)
**Eval**: pass@1=${(entry.evalScore.passAt1 * 100).toFixed(1)}%, regressions=${entry.evalScore.regressionCount}
**Hyperparams**: LoRA r=${entry.hyperparams.loraRank}, lr=${entry.hyperparams.learningRate}, epochs=${entry.hyperparams.epochs}
**Notes**: ${entry.notes}
`
}

export const ProvenanceLive = Provenance.Default
